### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by gabriel-maxx** [hkx3upper/Karlann#1]
hello i tested it on windows 7 x64 and it doesn't work could you support windows 7 please?

**Comment by HARM4Y** [comment]
Hello, Which version? Windows 7 x64 or Windows 7 x64 sp1? sp2?
I have tested it in Windows 7 sp1. It works.
Does DebugView not output keyboard scancode? Or does SocketTest not work well?

**Comment by HARM4Y** [comment]
![image](https://user-images.githubusercontent.com/41336794/190896333-b480bd47-6056-4c65-96fa-80b12a178fad.png)
Did you set Target OS Version == Windows 7?

**Comment by gabriel-maxx** [comment]
hello I just tested the new version you posted 4 hours ago on windows 7 sp1 and it worked, I had tested the old version 7 days ago (1.0.0.2) and the driver did not load, thanks for updating..
